include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - package_prefixed_library_names
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_breaks
    - unnecessary_statements
    - use_super_parameters
